### ISSUE TITLE
"This file is corrupted and should be moved to trash"

### ISSUE THREAD

**Issue by matronator** [dan-online/WebApps#1]
Or something like that, I don't know the precise English translation of the error notice. However, every app have the same warning pop-up when trying to launch it. At first I thought it was the usual warning you get when opening apps from unknown sources, but when I opened the Security preferences, there was no option to "open it anyways" as it is with other apps.

**Device**: MacBook Pro (Retina, 13-inch, Mid 2014)
**macOS**: Mojave 10.14.6
**CPU**: 3 GHz Intel Core i7
**Memory**: 16 GB 1600 MHz DDR3
**Graphics**: Intel Iris 1536 MB

**Comment by dan-online** [comment]
Hi @matronator, I have pushed all my source code to the repo. I am also uploading my built apps to [releases](https://github.com/dan-online/WebApps/releases), if these don't work I recommend building it yourself on your own computer by running ``npm run build`` in the folder of the app you would like, this should build and move it to your applications folder automatically! Feel free to mention me in this issue if you have any other problems or if it works! :)

**Comment by matronator** [comment]
All good now, thanks! :) Just a little sad about the removal of the Netflix app, but otherwise the builds all work just fine 👍

**Comment by dan-online** [comment]
The Netflix app needs a plugin that I am currently looking into adding
